repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.8"
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
  - repo: https://github.com/psf/black
    rev: "24.2.0"
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
