[tool.ruff]
fix = true
show-fixes = true
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = [
  "I", "F", "E", "W", "N", "D", "UP", "PL", "Q", "SIM", "TID", "ARG", "B", "TCH", "RET", "C4"
]
ignore = [
  "D202", "PLR2004", "D203", "D212", "ARG002", "RET505", "PLW2901", "SIM105", "ARG001",
  "PLC1901", "PLR5501", "RET508", "E501"
]

[tool.ruff.lint.pylint]
max-branches = 25
max-returns = 15
max-args = 10
max-statements = 50
